const Map<String, String> mapping = {
  "2 ": "Autos",
  "1 ": "Film",
  "10": "Music",
  "15": "Pets",
  "17": "Sports",
  "18": "Short Movies",
  "19": "Travel",
  "20": "Gaming",
  "21": "Videoblogging",
  "22": "People",
  "23": "Comedy",
  "24": "Entertainment",
  "25": "News",
  "26": "Howto",
  "27": "Education",
  "28": "Science",
  "29": "Nonprofits",
  "30": "Movies",
  "31": "Animation",
  "32": "Adventure",
  "33": "Classics",
  "34": "Comedy",
  "35": "Documentary",
  "36": "Drama",
  "37": "Family",
  "38": "Foreign",
  "39": "Horror",
  "40": "Sci-Fi/Fantasy",
  "41": "Thriller",
  "42": "Shorts",
  "43": "Shows",
  "44": "Trailers"
};
